-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
  ON I.ITEM_ID = T.ITEM_ID
WHERE NOT EXISTS(
    SELECT 1
    FROM ITEM_TREE C
    WHERE C.PARENT_ITEM_ID = I.ITEM_ID
)
ORDER BY ITEM_ID DESC