-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM ONLINE_SALE S
JOIN USER_INFO I
  ON S.USER_ID = I.USER_ID
GROUP BY YEAR, MONTH, I.GENDER
HAVING I.GENDER IS NOT NULL
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC