-- 코드를 입력하세요
# SELECT * from ANIMAL_OUTS
# order by datetime

SELECT HOUR(DATETIME) AS HOUR, COUNT(DISTINCT ANIMAL_ID)
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)