-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, H.CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) T
  ON H.CAR_ID = T.CAR_ID
WHERE H.START_DATE >= '2022-08-01' AND H.START_DATE < '2022-11-01'
GROUP BY MONTH, H.CAR_ID
ORDER BY MONTH ASC, H.CAR_ID DESC