-- 코드를 입력하세요
SELECT H.FLAVOR
FROM FIRST_HALF H
JOIN ICECREAM_INFO I
  ON H.FLAVOR = I.FLAVOR
WHERE H.TOTAL_ORDER > 3000 and I.INGREDIENT_TYPE = 'fruit_based'
GROUP BY H.FLAVOR
ORDER BY H.TOTAL_ORDER DESC