-- 코드를 입력하세요
SELECT F.CATEGORY,
       F.PRICE as MAX_PRICE,
       F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '김치', '국', '식용유')
    GROUP BY CATEGORY
) M
  ON F.CATEGORY = M.CATEGORY
 AND F.PRICE = M.MAX_PRICE
ORDER BY F.PRICE DESC