SELECT GRADE, ID, EMAIL
FROM (
    SELECT 
        CASE
            WHEN (D.SKILL_CODE & FE.FE_CODE) > 0 
             AND (D.SKILL_CODE & PY.PY_CODE) > 0 THEN 'A'
            WHEN (D.SKILL_CODE & CS.CS_CODE) > 0 THEN 'B'
            WHEN (D.SKILL_CODE & FE.FE_CODE) > 0 THEN 'C'
        END AS GRADE,
        D.ID,
        D.EMAIL
    FROM DEVELOPERS D
    JOIN (SELECT SUM(CODE) AS FE_CODE FROM SKILLCODES WHERE CATEGORY='Front End') FE
    JOIN (SELECT CODE AS PY_CODE FROM SKILLCODES WHERE NAME='Python') PY
    JOIN (SELECT CODE AS CS_CODE FROM SKILLCODES WHERE NAME='C#') CS
) T
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;
